### ISSUE TITLE
User Story: Sign-Up and Sign-In

### ISSUE THREAD

**Issue by MohamedElAbyad** [gabrielkarras/SOEN341#38]
* Priority: HIGH
* Risk: Normal
* User Story: As a user, I want to sign up and sign-in as either a client or a store admin so that can create and access my account according to my role

Test Description 1:  The client should be able to sign-up and fill up the sign-up form. Afterwards, the client should fill the sign-in form and have access to their account
Precondition: Client did not create a client account
Alternate Path:  If the client created an account they can proceed to signing-in
- [ ] Client clicks on "Sign-up" button
- [ ] Client fills out sign-up form
- [ ] Client clicks on "Complete Sign-up" button
- [ ] Client will be re-directed to the home page
- [ ] Client clicks on "Sign-in" button
- [ ] Client fills out sign-in form with name and password
- [ ] Client clicks on "login"
- [ ] Client will be redirected to their account page and should see their account details
Postcondition: Client must be able to re-login once they logged out

Test Description 2:  The store admin should be able to sign-up and fill up the sign-up form. Afterwards, they should fill the sign-in form and have access to their account
Precondition: The store admin did not create a store admin account
Alternate Path:  If the store admin created an account they can proceed to signing-in
- [ ] Store admin clicks on "Sign-up" button
- [ ] Store admin fills out sign-up form
- [ ] Store admin clicks on "Complete Sign-up" button
- [ ] Store admin will be re-directed to the home page
- [ ] Store admin clicks on "Sign-in" button
- [ ] Store admin fills out sign-in form with name and password
- [ ] Store admin clicks on "login"
- [ ] Store admin will be redirected to their account page and should see their account details
Postcondition: Store admin must be able to re-login once they logged out

**Comment by gabrielkarras** [comment]
Must re-open issue. We had trouble with some Django authentication modules as well as certain authentication APIs not being update for Django4.0. We will need to retackle this task for sprint 3.
